### ISSUE TITLE
can't run clearmap

### ISSUE THREAD

**Issue by AbsolemPillar** [ChristophKirst/ClearMap#17]
I'm been trying to get clearmap to work for a while but haven't any success. When I type python setup.py install I get this error message:

Settings: elastix path /usr/local/elastix does not exists, cf. Settings.py or type help(Settings) for details.
Settings: ilastik path /usr/local/ilastik-1.1.9-Linux does not exists, cf. Settings.py or type help(Settings) for details.

When I cd to Clearmap/Clearmap and open Settings.py, I don't know which one to edit? Also, am I suppost to pointed it the software or the directory?

thanks

**Comment by vzickus** [comment]
If you go to ClearMap\ClearMap you should find Settings.py. Starting line 29 you should see where to set the path to elastix:

https://github.com/ChristophKirst/ClearMap/blob/ae57ca9bc26b86ab8badaa6bf1223a7246dd10d4/ClearMap/Settings.py#L29

Then just set it to where you have it built/installed on your machine. For example, mine is:
`ElastixPath = '/home/asus/software/elastix-4.9.0-linux/';`

**Comment by AbsolemPillar** [comment]
thank you, vzickus by following your instruction. I was able to run sudo python setup.py install. it ran the setup fine.  the other part, where do I go to launch the clearmap software? I see a couple of new folders created after I ran setup.

build  ClearMap  ClearMap.egg-info  dist

**Comment by vzickus** [comment]
I suggest you have a read of this, where they point you to the relevant files
 https://github.com/ChristophKirst/ClearMap/blob/master/docs/tutorial.rst

**Comment by AbsolemPillar** [comment]
thank you, I have read the tutorials a few times. I kind of left everything as default just see how it works besides changing the path to this:
#load the parameters:
execfile('/home/moduk/ClearMap/build/lib.linux-x86_64-2.7/ClearMap/Scripts/parameter_file_template.py')

then I ran: python process_template.py
could help me see if this suppose to happen? 

Elastix sucessfully initialized from path: /home/moduk/elastix490
Ilastik sucessfully initialized from path: /home/moduk/ilastik-1.3.0-Linux
Traceback (most recent call last):
  File "process_template.py", line 7, in <module>
    execfile('/home/moduk/ClearMap/build/lib.linux-x86_64-2.7/ClearMap/Scripts/parameter_file_template.py')
  File "/home/moduk/ClearMap/build/lib.linux-x86_64-2.7/ClearMap/Scripts/parameter_file_template.py", line 17, in <module>
    from ClearMap.Analysis.Label import countPointsInRegions
  File "/usr/local/lib/python2.7/dist-packages/ClearMap-0.9.2-py2.7-linux-x86_64.egg/ClearMap/Analysis/Label.py", line 164, in <module>
    Label = LabelInfo();
  File "/usr/local/lib/python2.7/dist-packages/ClearMap-0.9.2-py2.7-linux-x86_64.egg/ClearMap/Analysis/Label.py", line 86, in __init__
    slf.initialize(annotationFile = annotationFile);
  File "/usr/local/lib/python2.7/dist-packages/ClearMap-0.9.2-py2.7-linux-x86_64.egg/ClearMap/Analysis/Label.py", line 91, in initialize
    with open(annotationFile) as dfile:
IOError: [Errno 2] No such file or directory: '/usr/local/lib/python2.7/dist-packages/ClearMap-0.9.2-py2.7-linux-x86_64.egg/ClearMap/Data/ARA2_annotation_info_collapse.csv'

**Comment by crazyhottommy** [comment]
@AbsolemPillar I am trying Clearmap as well and got the same error. I then copied the `Data` folder from your git clone download

```
ls Data/
ARA2_annotation_info_collapse.csv  ARA2_annotation_statistics.csv       lightsheet_line_intensty_profiles_y.csv
ARA2_annotation_info.csv           lightsheet_flatfield_correction.csv  lightsheet_peak_intensity_profile_y.csv

cp -r Data /usr/local/lib/python2.7/dist-packages/ClearMap-0.9.2-py2.7-linux-x86_64.egg/ClearMap/
```
it should work.

**Comment by auesro** [comment]
It does.
For some reason, when python installs the repository it does not copy the Data folder. You need to add it manually as per @crazyhottommy code.
