### ISSUE TITLE
Numpy module not found!

### ISSUE THREAD

**Issue by enovinbakht** [ChristophKirst/ClearMap#36]
Hi, I am having several issues with the parameter file and run file for clearmap. My first issue is that when attempting to run the command "Registration Alignment Parameter" it says that the operation is not defined. My second issue is that when my numpy module was not found when I was trying to run the run file. Here is the error that I receive when attempting to run that file. 

>>> exec(open('/home/rieralab/Clearmap/ClearMap/Scripts/parameter_file_template.py').read())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<string>", line 8, in <module>
ModuleNotFoundError: No module named 'numpy'

Thanks for all the help in advance.

**Comment by enovinbakht** [comment]
UPDATE:
I am running the code in Spydera and when I run the parameter file it returns an errors stating that "Import error: No module named ClearMap.Settings". I am not sure how I am supposed to manually import these modules because it seems like there are not automatically being downloaded.
