### ISSUE TITLE
ValueError: setting an array element with a sequence in countPointsInRegions()

### ISSUE THREAD

**Issue by pforai** [ChristophKirst/ClearMap#6]
```Python
Traceback (most recent call last):
  File "process_template_1.py", line 91, in <module>
    ids, counts = countPointsInRegions(points, labeledImage = AnnotationFile, intensities = intensities, intensityRow = 0);
  File "/groups/keays/software/clearmap/lib/python2.7/site-packages/ClearMap-0.9.2-py2.7.egg/ClearMap/Analysis/Label.py", line 234, in countPointsInRegions
    pointLabels = labelPoints(points, labeledImage, level = level, collapse = collapse);
  File "/groups/keays/software/clearmap/lib/python2.7/site-packages/ClearMap-0.9.2-py2.7.egg/ClearMap/Analysis/Label.py", line 218, in labelPoints
    pointLabels[i] = labelImage[int(x[i]), int(y[i]), int(z[i])];
ValueError: setting an array element with a sequence.
```

Any idea what's wrong here?

**Comment by ChristophKirst** [comment]
Sorry, without the precise code you executed to set the parameters etc its impossible to debug this, please post this code.

**Comment by pforai** [comment]
Ah, it seems to come from the fact that AnnotationFile is actually hard coded in ClearMap-0.9.2-py2.7.egg/ClearMap/Analysis/Label.py and I don't have the file in this location. Will investigate further.
